services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./ha-config:/config
      - ./dist:/config/www/lcars
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
    environment:
      - TZ=America/New_York
    restart: always
    privileged: true
    group_add:
      - dialout
    ports:
      - '8123:8123'
      - '80:80'
      - '8300:8300'
      - '51827:51827'
