type: custom:lcars-custom-card
vars:
  lcars_unit: 3.2vw
children:
  - props:
      class: lcars-col
    children:
      - type: LPanel
        props:
          fillWidth: true
          fillHeight: true
          color: var(--lcars-color-dodger-blue)
          leftColor: var(--lcars-color-dodger-blue)
          bottomHeight: 0.5
          bottomOuterRadX: 3
          bottomInnerRadX: 2
          bottomInnerRadY: 1
          class: lcars-margin-bottom-3
        leftChildren:
          - props:
              class:
                - lcars-el
                - button
                - lcars-lilac-bg
                - lcars-h-1
                - relative
                - lcars-margin-bottom-1
            children:
              - text: LCARS 23295
                props:
                  class: lcars-black-color bottom-right
          - text: 01-23564
            props:
              class:
                - lcars-el
                - lcars-dodger-blue-bg
                - lcars-pad-4
                - lcars-black-color
              style:
                textAlign: right
        bottomChildren:
          - props:
              class:
                - lcars-el
                - lcars-golden-tanoi-bg
                - bottom
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .5)
              width: calc(var(--lcars-unit) * .75)
          - props:
              class:
                - lcars-el
                - lcars-lilac-bg
                - bottom
                - lcars-w-1-plus
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .5)
          - props:
              class:
                - lcars-el
                - lcars-lilac-bg
                - bottom
                - lcars-w-3
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .5)
          - props:
              class:
                - lcars-el
                - lcars-indian-red-bg
                - bottom
                - lcars-w-1
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .5)
        children:
          - text: Planetary Catelog Database 93-6636
            props:
              class: lcars-font-10 lcars-golden-tanoi-color lcars-margin-bottom-6
              style:
                textAlign: right
          - props:
              class: lcars-row
            children:
              - props:
                  class: lcars-col
                children:
                  - tag: table
                    props:
                      class: lcars-margin-left-10 lcars-table scanning right
                    style:
                      fontSize: calc(var(--lcars-unit) * 0.5)
                      lineHeight: calc(var(--lcars-unit) * 0.6)
                    children:
                      - tag: tr
                        children:
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: temperature
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: dew_point
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: humidity
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: cloud_coverage
                      - tag: tr
                        children:
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: uv_index
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: pressure
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: wind_bearing
                          - tag: td
                            children:
                              - type: HAStateValue
                                props:
                                  entity: weather.forecast_home
                                  attribute: wind_speed
              - props:
                  class: lcars-col fill right
                children:
                  - props:
                      class: lcars-row right lcars-margin-bottom-3
                    children:
                      - text: 07-3215
                        props:
                          class:
                            - lcars-dodger-blue-bg
                            - lcars-black-color
                            - lcars-el
                            - lcars-w-1
                            - lcars-h-unit
                            - rad-2
                            - lcars-font-6
                            - lcars-pad-4
                            - centered
                            - lcars-margin-right-3
                      - text: 03-4984
                        props:
                          class:
                            - lcars-atomic-tangerine-bg
                            - lcars-black-color
                            - lcars-el
                            - lcars-w-1
                            - lcars-h-unit
                            - rad-2
                            - lcars-font-6
                            - lcars-pad-4
                            - centered
                  - props:
                      class: lcars-row right
                    children:
                      - text: 08-2501
                        props:
                          class:
                            - lcars-lilac-bg
                            - lcars-black-color
                            - lcars-el
                            - lcars-w-1
                            - lcars-h-unit
                            - rad-2
                            - lcars-font-6
                            - lcars-pad-4
                            - centered
                            - lcars-margin-right-3
                      - text: 04-2809
                        props:
                          class:
                            - lcars-indian-red-bg
                            - lcars-black-color
                            - lcars-el
                            - lcars-w-1
                            - lcars-h-unit
                            - rad-2
                            - lcars-font-6
                            - lcars-pad-4
                            - centered
      - type: PPanel
        props:
          fillWidth: true
          fillHeight: true
          color: var(--lcars-color-indian-red)
          leftColor: var(--lcars-color-indian-red)
          topHeight: 0.5
          topOuterRadX: 3
          topInnerRadX: 2
          topInnerRadY: 1
        topChildren:
          - props:
              class:
                - lcars-el
                - lcars-golden-tanoi-bg
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .5)
              width: calc(var(--lcars-unit) * .75)
          - props:
              class:
                - lcars-el
                - lcars-atomic-tangerine-bg
                - lcars-w-1-plus
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .25)
          - props:
              class:
                - lcars-el
                - lcars-lilac-bg
                - lcars-w-3
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .5)
          - props:
              class:
                - lcars-el
                - lcars-indian-red-bg
                - lcars-w-1
                - lcars-margin-left-1
                - lcars-margin-right-1
            style:
              height: calc(var(--lcars-unit) * .5)
        leftChildren:
          - props:
              class:
                - lcars-el
                - button
                - lcars-indian-red-bg
                - lcars-h-unit
                - relative
                - lcars-margin-bottom-1
            children:
              - text: 02-24156
                props:
                  class: lcars-black-color bottom-right
          - props:
              class:
                - lcars-el
                - button
                - lcars-indian-red-bg
                - lcars-h-1-plus
                - relative
                - lcars-margin-bottom-1
            children:
              - text: 03-41248
                props:
                  class: lcars-black-color bottom-right
          - props:
              class:
                - lcars-el
                - button
                - lcars-golden-tanoi-bg
                - lcars-h-unit
                - relative
                - lcars-margin-bottom-1
            children:
              - text: 04-14702
                props:
                  class: lcars-black-color bottom-right
          - text: 05-32456
            props:
              class:
                - lcars-el
                - button
                - lcars-atomic-tangerine-bg
                - lcars-black-color
                - lcars-h-1-plus
                - relative
                - lcars-margin-bottom-1
                - lcars-pad-4
              style:
                textAlign: right
        children:
          - props:
              class: lcars-row
            children:
              - props:
                  class: clars-col lcars-margin-left-10
                children:
                  - text: Sol
                    props:
                      class:
                        - lcars-golden-tanoi-color
                        - lcars-font-10
                        - lcars-margin-bottom-5
                  - type: EntityAttributeList
                    props:
                      entity: sun.sun
                      scanning: true
                      class: lcars-lilac-color
                      style:
                        fontSize: calc(var(--lcars-unit) * 0.5)
                        lineHeight: calc(var(--lcars-unit) * 0.6)
              - type: OPanel
                props:
                  class: lcars-margin-left-5
                  leftWidth: 1
                  rightWidth: 1
                  topLeftOuterRadX: 2
                  topRightOuterRadX: 2
                  bottomLeftOuterRadX: 2
                  bottomRightOuterRadX: 2
                  topHeight: 0.5
                  bottomHeight: 0.5
                  color: var(--lcars-color-indian-red)
                  leftColor: var(--lcars-color-indian-red)
                  rightColor: var(--lcars-color-indian-red)
                topChildren:
                  - props:
                      class:
                        - lcars-el
                        - lcars-w-unit
                        - lcars-indian-red-bg
                      style:
                        height: calc(var(--lcars-unit) * 0.5)
                  - props:
                      class: lcars-el fill lcars-h-unit lcars-black-bg
                  - props:
                      class:
                        - lcars-el
                        - lcars-w-unit
                        - lcars-indian-red-bg
                      style:
                        height: calc(var(--lcars-unit) * 0.5)
                bottomChildren:
                  - props:
                      class:
                        - lcars-el
                        - lcars-w-unit
                        - lcars-indian-red-bg
                        - bottom
                      style:
                        height: calc(var(--lcars-unit) * 0.5)
                  - props:
                      class: lcars-el fill lcars-h-unit lcars-black-bg
                  - props:
                      class:
                        - lcars-el
                        - lcars-w-unit
                        - lcars-indian-red-bg
                        - bottom
                      style:
                        height: calc(var(--lcars-unit) * 0.5)
                children:
                  - tag: img
                    props:
                      src: >-
                        https://www.nasa.gov/wp-content/uploads/2016/07/10f0.15.gif?w=500
                      style:
                        width: calc(var(--lcars-unit) * 8)
                        marginLeft: calc(var(--lcars-unit) * 2)
                        marginRight: calc(var(--lcars-unit) * 2)
