type: custom:ha-lcars-panel
vars:
  lcars_unit: 30pt
mixins:
  myText:
    type: el
    fontSize: 0.4
    alignContent: bottom-right
    height: 2
    width: 3
    radXTopLeft: 1
    radXBottomLeft: 1
children:
  - type: panel-tl
    color: golden-tainoi
    fillWidth: true
    fillHeight: true
    leftColor: golden-tainoi
    leftPad: 1
    leftWidth: 4
    leftChildren:
      - type: row
        children:
          - type: el
            nav: /home
            text: Home
            color: golden-tainoi
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: golden-tainoi
            showForNav: /home
      - type: row
        children:
          - type: el
            nav: /demo/config
            text: Config
            color: dodger-blue
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: dodger-blue
            showForNav: /demo/config
      - type: row
        children:
          - type: el
            nav: /demo/layout
            text: Layout
            color: indian-red
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: indian-red
            showForNav: /demo/layout
      - type: row
        children:
          - type: el
            nav: /demo/elements
            text: Elements
            color: atomic-tangerine
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: atomic-tangerine
            showForNav: /demo/elements
      - type: row
        children:
          - type: el
            nav: /demo/panels
            text: Panels
            color: fiery-orange
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: fiery-orange
            showForNav: /demo/panels
      - type: row
        children:
          - type: el
            nav: /demo/nav
            text: Navigation
            color: anakiwa
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: anakiwa
            showForNav: /demo/nav
      - type: row
        children:
          - type: el
            nav: /demo/state
            text: HA State
            color: lilac
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: lilac
            showForNav: /demo/state
      - type: row
        children:
          - type: el
            nav: /demo/actions
            text: Actions
            color: dodger-blue
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: dodger-blue
            showForNav: /demo/actions
      - type: row
        children:
          - type: el
            nav: /demo/themes
            text: Themes
            color: indian-red
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: indian-red
            showForNav: /demo/themes
      - type: row
        children:
          - type: el
            nav: /demo/remote
            text: Remote Config
            color: fiery-orange
            textColor: black
            width: 4
          - type: pill
            width: 1
            color: fiery-orange
            showForNav: /demo/remote
    children:
      - showForNav: /home
        type: remote
        url: ~/demo/home.yaml
      - showForNav: /demo/config
        type: remote
        url: ~/demo/config.yaml
      - showForNav: /demo/layout
        type: remote
        url: ~/demo/layout.yaml

      - showForNav: /demo/elements
        type: remote
        url: ~/demo/elements.yaml

      - showForNav: /demo/panels
        type: remote
        url: ~/demo/panels.yaml

      - showForNav: /demo/nav
        type: remote
        url: ~/demo/nav.yaml

      - showForNav: /demo/state
        type: remote
        url: ~/demo/state.yaml

      - showForNav: /demo/actions
        type: remote
        url: ~/demo/actions.yaml

      - showForNav: /demo/themes
        type: remote
        url: ~/demo/themes.yaml

      - showForNav: /demo/remote
        type: remote
        url: ~/demo/remote.yaml
