type: custom:ha-lcars-panel
vars:
  lcars_unit: 2vw
nav:
  - key: home
    text: Home
  - key: config
    text: Config
    children:
      - key: globals
        text: Globals
  - key: layout
    text: Layout
  - key: elements
    text: Elements
  - key: panels
    text: Panels
  - key: nav
    text: Navigation
  - key: state
    text: HA State
  - key: actions
    text: Actions
mixins:
  myText:
    type: el
    fontSize: 0.4
    alignContent: bottom-right
    height: 2
    width: 3
    radXTopLeft: 1
    radXBottomLeft: 1
  myMixin:
    color: orange-peel
  menuTab:
    type: el
    alignContent: middle-center
    width: 3
    textColor: black
children:
  - type: panel-tl
    color: golden-tainoi
    fillWidth: true
    fillHeight: true
    leftColor: golden-tainoi
    leftPad: 1
    leftWidth: 4
    leftChildren:
      - type: menu-vertical
        width: 4
        height: 1
        navToFirstChild: true
    children:
      - showForNav: /home
        children:
          - type: remote
            url: ~/demo/home.yaml
          - type: pill
            color: dodger-blue
            nav: /config/globals
            text: Start Demo
      - showForNav: /config
        children:
          - type: remote
            url: ~/demo/config.yaml
          - type: pill
            color: indian-red
            text: layout
            nav: /layout/unit
      - showForNav: /layout
        children:
          - type: remote
            url: ~/demo/layout.yaml
          - type: pill
            color: atomic-tangerine
            text: elements
            nav: /elements/element
      - showForNav: /elements
        children:
          - type: remote
            url: ~/demo/elements.yaml
          - type: pill
            nav: /panels/types
            color: fiery-orange
            text: Panels
      - showForNav: /panels
        children:
          - type: remote
            url: ~/demo/panels.yaml
          - type: pill
            color: anakiwa
            nav: /nav/local
            text: Navigation
      - showForNav: /nav
        children:
          - type: remote
            url: ~/demo/nav.yaml
          - type: pill
            color: lilac
            nav: /state/value
            text: HA State
      - showForNav: /state
        children:
          - type: remote
            url: ~/demo/state.yaml
          - type: pill
            color: dodger-blue
            nav: /actions/tap
            text: Actions
      - showForNav: /actions
        type: remote
        url: ~/demo/actions.yaml
