type: custom:ha-lcars-panel
vars:
  lcars_unit: 2vw
children:
  - showForNav: /home
    children:
      - type: el
        text: Welcome to ha-lcars-panel
        textColor: golden-tainoi
        fontSize: 1
      - type: panel-all
        color: dodger-blue
        fillWidth: true
        leftColor: dodger-blue
        rightColor: dodger-blue
        children:
          - type: el
            text: |
              Unlike the LCARS Home Assistant theme, this is a comprehensive LCARS system designed to allow you to create 
              complex LCARS layouts. Everything in this system is sized in "LCARS Units". What is an LCARS Unit you ask? this
              is an LCARS Unit:
          - tag: pre
            text: |
              vars:
                lcars_unit: 2vw
              children:
                - showForNav: /home
                  children:
                    - type: el
                      text: Welcome to ha-lcars-panel
                      textColor: golden-tainoi
                      fontSize: 1
                    - type: panel-all
                      color: dodger-blue
                      fillWidth: true
                      leftColor: dodger-blue
                      rightColor: dodger-blue
                      children:
                        - type: el
                          text: |
                            Unlike the LCARS Home Assistant theme, this is a comprehensive LCARS system designed to allow you to create 
                            complex LCARS layouts. Everything in this system is sized in "LCARS Units". What is an LCARS Unit you ask? this
                            is an LCARS Unit:
