type: custom:ha-lcars-panel
vars:
  lcars_unit: 3vw
mixins:
  myText:
    type: el
    fontSize: 0.4
    alignContent: bottom-right
    height: 2
    width: 3
    radXTopLeft: 1
    radXBottomLeft: 1
  myMixin:
    color: orange-peel
  menuTab:
    type: el
    alignContent: middle-center
    width: 3
    textColor: black
children:
  - type: panel-tl
    color: golden-tainoi
    fillWidth: true
    fillHeight: true
    leftColor: golden-tainoi
    leftPad: 1
    leftWidth: 4
    leftChildren:
      - type: row
        children:
          - type: el
            nav: /home
            text: Home
            color: golden-tainoi
            textColor: black
            width: 4
            height: 1
      - type: row
        children:
          - type: el
            nav: /demo/config/globals
            text: Config
            color: dodger-blue
            textColor: black
            width: 4
            height: 1
      - type: row
        children:
          - type: el
            nav: /demo/layout/unit
            text: Layout
            color: indian-red
            textColor: black
            width: 4
            height: 1
      - type: row
        children:
          - type: el
            nav: /demo/elements/element
            text: Elements
            color: atomic-tangerine
            textColor: black
            width: 4
            height: 1
      - type: row
        children:
          - type: el
            nav: /demo/panels/types
            text: Panels
            color: fiery-orange
            textColor: black
            width: 4
            height: 1
      - type: row
        children:
          - type: el
            nav: /demo/nav/local
            text: Navigation
            color: anakiwa
            textColor: black
            width: 4
            height: 1
      - type: row
        children:
          - type: el
            nav: /demo/state/value
            text: HA State
            color: lilac
            textColor: black
            width: 4
            height: 1
      - type: row
        children:
          - type: el
            nav: /demo/actions/tap
            text: Actions
            color: dodger-blue
            textColor: black
            width: 4
            height: 1
    children:
      - showForNav: /home
        type: remote
        url: ~/demo/home.yaml
      - showForNav: /demo/config
        type: remote
        url: ~/demo/config.yaml
      - showForNav: /demo/layout
        type: remote
        url: ~/demo/layout.yaml
      - showForNav: /demo/elements
        type: remote
        url: ~/demo/elements.yaml
      - showForNav: /demo/panels
        type: remote
        url: ~/demo/panels.yaml
      - showForNav: /demo/nav
        type: remote
        url: ~/demo/nav.yaml
      - showForNav: /demo/state
        type: remote
        url: ~/demo/state.yaml
      - showForNav: /demo/actions
        type: remote
        url: ~/demo/actions.yaml
      - showForNav: /demo/themes
        type: remote
        url: ~/demo/themes.yaml
      - showForNav: /demo/remote
        type: remote
        url: ~/demo/remote.yaml
