type: custom:ha-lcars-panel
vars:
  lcars_unit: 5vw
children:
  - type: row
    children:
      - type: col
        children:
          - type: el
            color: grey
            width: 6.5
            height: 2
            radXInnerTopRight: 1
            radYInnerTopRight: 1
          - type: el
            color: shark
            height: 2
            width: 5.5
            marginLeft: 1
            radXInnerTopRight: 1.5
            radYInnerTopRight: 1
          - type: col
            width: 4
            gap: 1
            marginLeft: 1
            children:
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: indian-red
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: indian-red
                    text: "01"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: indian-red
                    textColor: black
                    padLeft: 0.2
                    text: Starship Map
                    nav: /map
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: atomic-tangerine
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: atomic-tangerine
                    text: "02"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: atomic-tangerine
                    textColor: black
                    padLeft: 0.2
                    text: Navigation
                    nav: /nav
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: periwinkle
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: peiwinkle
                    text: "03"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: periwinkle
                    textColor: black
                    padLeft: 0.2
                    text: Sensors
                    nav: /sensors
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: dodger-blue
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: dodger-blue
                    text: "04"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: dodger-blue
                    textColor: black
                    padLeft: 0.2
                    text: Communication
                    nav: /comms
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: lilac
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: lilac
                    text: "05"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: lilac
                    textColor: black
                    padLeft: 0.2
                    text: Transporter
                    nav: /beam
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: pot-pourri
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: pot-pourri
                    text: "06"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: pot-pourri
                    textColor: black
                    padLeft: 0.2
                    text: Holodeck
                    nav: /holo
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: dodger-blue
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: dodger-blue
                    text: "07"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: dodger-blue
                    textColor: black
                    padLeft: 0.2
                    text: Medical
                    nav: /bones
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: indian-red
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: indian-red
                    text: "08"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: indian-red
                    textColor: black
                    padLeft: 0.2
                    text: Tactical
                    nav: /tactical
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: atomic-tangerine
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: atomic-tangerine
                    text: "09"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: atomic-tangerine
                    textColor: black
                    padLeft: 0.2
                    text: Engineering
                    nav: /scotty
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: dodger-blue
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: dodger-blue
                    text: "10"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: dodger-blue
                    textColor: black
                    padLeft: 0.2
                    text: Science
                    nav: /sci
              - type: row
                children:
                  - type: el
                    width: 0.5
                    height: 1
                    color: indian-red
                    capLeft: 0.5
                  - type: el
                    width: 1
                    fontSize: 1
                    textColor: indian-red
                    text: "11"
                  - type: el
                    width: 3.8
                    fontSize: 0.5
                    color: indian-red
                    textColor: black
                    padLeft: 0.2
                    text: Command
                    nav: /bridge
          - type: el
            color: shark
            height: 2
            width: 5.5
            marginLeft: 1
            radXInnerBottomRight: 1.5
            radYInnerBottomRight: 1
          - type: el
            color: grey
            width: 6.5
            height: 2
            radXInnerBottomRight: 1
            radYInnerBottomRight: 1
      - type: col
        children:
          - showForNav: /map
            text: Starship Map
          - showForNav: /nav
            text: Navigation
          - showForNav: /sensors
            text: Sensors
          - showForNav: /comms
            text: Hailing frequency
          - showForNav: /beam
            text: One to beam up
          - showForNav: /holo
            text: Holodeck
          - showForNav: /bones
            text: I'm a doctor, not a miracle worker.
          - showForNav: /tactical
            text: Tactical
          - showForNav: /scotty
            text: Scotty, I need more power!
          - showForNav: /sci
            text: Science
          - showForNav: /bridge
            text: Kirk here.
