type: custom:lcars-custom-card
vars:
  lcars_unit: 2vw
children:
  - showForNav: /home
    children:
      - type: panel-bl
        color: golden-tainoi
        fillWidth: true
        fillHeight: true
        leftColor: golden-tainoi
        leftPad: 1
        children:
          - type: el
            text: Welcome to ha-lcars-panel
            textColor: golden-tainoi
            fontSize: 1
          - tag: p
            text: |
              This is not just a "custom card" for Home Assistant. It is a comprehensive LCARS system designed to allow
              you to create complex LCARS layouts either as a single card in a dashboard using the LCARS theme, create
              an entire Lovelace dashboard with a single card, or create a custom panel that runs full-screen without
              the Home Assistant menu.
          - tag: p
            text: |
              Click the button below to start a detailed demo
          - type: pill
            color: dodger-blue
            nav: /demo/config
            text: Start Demo
  - showForNav: /demo/config
    type: panel-tl
    title: Configuration
    color: dodger-blue
    fillWidth: true
    fillHeight: true
    leftColor: dodger-blue
    leftPad: 1
    topCap: true
    children:
      - tag: p
        text: |
          The top-level card configuration is as follows:
      - tag: pre
        text: |
          type: custom:lcars-custom-card
          vars:
            lcars_unit: 2vw
          children:
            - text: Hello LCARS!
      - tag: p
        text: |
          The first line is standard for all Home Asistant custom cards an simply specifies the card type.
      - tag: pre
        text: |
          type: custom:lcars-custom-card
      - tag: p
        text: |
          The vars key allows you to modify global variables. The following variables are available:
      - tag: pre
        text: |
          lcars_unit: Sets the unit size as a valid CSS size such as 50px, 3rem, 3em (Default is 2vw)
          lcars_color_bg: Sets the main background color (Default is black #000000)
          lcars_color_text: Sets the default text color (Default is periwinkle #C3CDE6)
      - tag: p
        text: |
          You can override any global CSS variable using this vars key. Simply remove the leading dashes from the
          variable name and replace any dashes in the name with underscores.
      - tag: p
        text: |
          The children key allows you to provide a list of items available for display directly in the top level 
          container. The reason they are "available for display" is because they can be shown conditionally based
          on navigation. Each item has the following properties:
      - tag: pre
        text: |
          type: Used to specify a custom LCARS element
          tag: Any html tag (ex: a, div, p)
          text: Text that will be passed directly as content of the element or tag
          showForNav: Navigation path where item is visible
          children: List of items to be rendered inside the element or tag
          leftChildren: List of items to be rendered inside the left portion of the element or tag if supported
          rightChildren: List of items to be rendered inside the right portion of the element or tag if supported
          topChildren: List of items to be rendered inside the top portion of the element or tag if supported
          bottomChildren: List of items to be rendered inside the bottom portion of the element or tag if supported

      - type: row
        gap: 1
        children:
          - type: pill
            color: golden-tainoi
            text: home
            nav: /home
          - type: pill
            color: indian-red
            text: layout
            nav: /demo/layout
  - showForNav: /demo/layout
    type: panel-tl
    title: Configuration
    color: indian-red
    fillWidth: true
    fillHeight: true
    leftColor: indian-red
    leftPad: 1
    topCap: true
    children:
      - tag: p
        text: |
          The layout system is based on LCARS Units. This is a 1 unit x 1 unti square:
      - type: el
        width: 1
        height: 1
        color: golden-tainoi
      - tag: p
        text: |
          The layout system uses the "flexbox" CSS layout meaning items are flexibly displayed in rows and columns.
      - type: row
        gap: 1
        children:
          - type: pill
            color: golden-tainoi
            text: home
            nav: /home
          - type: pill
            color: dodger-blue
            text: config
            nav: /demo/config
