type: custom:ha-lcars-panel
vars:
  lcars_unit: 3vw
children:
  - type: panel-tl
    color: golden-tainoi
    fillWidth: true
    fillHeight: true
    leftColor: golden-tainoi
    leftPad: 1
    leftChildren:
      - type: el
        nav: /home
        text: Layout
        color: indian-red
        textColor: black
      - type: el
        nav: /demo/elements
        text: Elements
        color: atomic-tangerine
        textColor: black
      - type: el
        nav: /demo/panels
        text: Panels
        color: fiery-orange
        textColor: black
      - type: el
        nav: /demo/nav
        text: Navigation
        color: anakiwa
        textColor: black
      - type: el
        nav: /demo/state
        text: HA State
        color: lilac
        textColor: black
    children:
      - showForNav: /home2
        children:
          - type: sample
            configYaml: |
              - type: col
                children:
                  - type: el
                    width: 1
                    height: 1
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    height: 1
                    color: indian-red
                  - type: el
                    width: 1
                    height: 1
                    color: dodger-blue

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                children:
                  - type: el
                    width: 1
                    height: 1
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    height: 1
                    color: indian-red
                  - type: el
                    width: 1
                    height: 1
                    color: dodger-blue

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                children:
                  - type: el
                    width: 1
                    height: 2
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    height: 0.5
                    color: indian-red
                  - type: el
                    width: 1
                    height: 1
                    color: dodger-blue

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                bottom: true
                children:
                  - type: el
                    width: 1
                    height: 2
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    height: 0.5
                    color: indian-red
                  - type: el
                    width: 1
                    height: 1
                    color: dodger-blue

          - type: sample
            configYaml: |
              - type: col
                gap: 1
                style:
                  width: calc(var(--lcars-unit) * 3)
                children:
                  - type: row
                    children:
                      - type: el
                        width: 3
                        height: 1
                        color: atomic-tangerine
                  - type: row
                    right: true
                    gap: 1
                    children:
                      - type: el
                        width: 1
                        height: 1
                        color: indian-red
                      - type: el
                        width: 1
                        height: 1
                        color: dodger-blue

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                stretch: true
                children:
                  - type: el
                    width: 1
                    height: 2
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    color: indian-red
                  - type: el
                    width: 1
                    color: dodger-blue

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                children:
                  - type: el
                    width: 1
                    height: 1
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    height: 1
                    color: indian-red
                  - type: el
                    width: 1
                    height: 1
                    color: dodger-blue
              - type: row
                gap: 1
                stretch: true
                children:
                  - type: el
                    width: 1
                    height: 1
                    color: golden-tainoi
                  - type: el
                    width: 1
                    color: lilac
                  - type: el
                    width: 1
                    color: fiery-orange

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                marginBottom: 1
                stretch: true
                children:
                  - type: el
                    width: 1
                    height: 1
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    color: indian-red
                  - type: el
                    width: 1
                    color: dodger-blue
              - type: row
                gap: 1
                stretch: true
                children:
                  - type: el
                    width: 1
                    height: 1
                    color: golden-tainoi
                  - type: el
                    width: 1
                    color: lilac
                  - type: el
                    width: 1
                    color: fiery-orange

          - type: sample
            configYaml: |
              - type: el
                color: golden-tainoi
                children:
                  - type: row
                    pad: 1
                    fill: false
                    children:
                      - type: el
                        width: 1
                        height: 1
                        color: atomic-tangerine
                      - type: el
                        width: 1
                        color: indian-red
                      - type: el
                        width: 1
                        color: dodger-blue

          - type: pill
            color: atomic-tangerine
            text: elements
            nav: /demo/elements

      - showForNav: /demo/elements
        children:
          - type: sample
            configYaml: |
              - type: el
                width: 1
                height: 1
                color: golden-tainoi

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                children:
                  - type: el
                    width: 1
                    height: 1
                    color: indian-red
                  - type: el
                    width: 1
                    height: 1
                    color: atomic-tangerine
                  - type: el
                    width: 1
                    height: 1
                    color: golden-tainoi
                  - type: el
                    width: 1
                    height: 1
                    color: green
                  - type: el
                    width: 1
                    height: 1
                    color: dodger-blue
                  - type: el
                    width: 1
                    height: 1
                    color: indigo
                  - type: el
                    width: 1
                    height: 1
                    color: lilac

          - type: sample
            configYaml: |
              - type: row
                gap: 1
                children:
                  - type: el
                    width: 2
                    height: 1
                    color: dodger-blue
                  - type: el
                    width: 1
                    height: 2
                    color: indian-red

          - type: sample
            configYaml: |
              - type: el
                fontSize: 0.5
                text: fontSize 0.5
              - type: el
                fontSize: 1
                text: fontSize 1
              - type: el
                fontSize: 2
                text: fontSize 2

          - type: sample
            configYaml: |
              - type: el
                fontSize: 1
                lineHeight: 1
                color: golden-tainoi
                textColor: black
                text: lineHeight 1
              - type: el
                fontSize: 1
                lineheight: 1.2
                color: dodger-blue
                textColor: black
                text: lineHeight 1.2

          - type: sample
            configYaml: |
              - type: el
                textColor: golden-tainoi
                text: golden-tainoi
              - type: el
                textColor: indian-red
                text: indian-red

          - type: sample
            configYaml: |
              - type: el
                width: 10
                height: 5
                color: dodger-blue
                textColor: black
                alignContent: bottom-right
                text: bottom-right

          - type: sample
            configYaml: |
              - type: el
                width: 2
                height: 1
                color: golden-tainoi
                capRight: true

          - type: sample
            configYaml: |
              - type: el
                width: 4
                height: 4
                radXTopLeft: 1
                color: golden-tainoi
                marginBottom: 1

          - type: sample
            configYaml: |
              - type: el
                width: 4
                height: 4
                radXTopLeft: 1
                radYTopLeft: 2
                color: golden-tainoi

          - type: sample
            configYaml: |
              - type: el
                width: 4
                height: 4
                radXInnerTopLeft: 1
                radYInnerTopLeft: 1
                color: golden-tainoi
          - type: sample
            configYaml: |
              - type: el
                width: 4
                height: 1
                fontSize: 0.5
                textColor: black
                alignContent: middle-center
                color: golden-tainoi
                capRight: true
                capLeft: true
                button: true
                text: button

          - type: pill
            nav: /demo/panels
            color: fiery-orange
            text: Panels

      - showForNav: /home
        children:
          - type: sample
            configYaml: |
              - type: panel-tl
                color: dodger-blue
                children:
                  - type: el
                    width: 4
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content
          - type: sample
            configYaml: |
              - type: panel-tl
                title: title
                color: dodger-blue
                gap: 1
                leftWidth: 1
                leftColor: golden-tainoi
                topCap: true
                bottomCap: true
                leftChildren:
                  - type: el
                    color: atomic-tangerine
                    height: 1
                topChildren:
                  - type: el
                    color: lilac
                    width: 1
                children:
                  - type: el
                    width: 8
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content

          - type: sample
            configYaml: |
              - type: panel-bl
                color: dodger-blue
                children:
                  - type: el
                    width: 4
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content
          - type: sample
            configYaml: |
              - type: panel-bl
                title: title
                color: dodger-blue
                gap: 1
                leftWidth: 1
                leftColor: golden-tainoi
                topCap: true
                bottomCap: true
                leftChildren:
                  - type: el
                    color: atomic-tangerine
                    height: 1
                bottomChildren:
                  - type: el
                    color: lilac
                    width: 1
                children:
                  - type: el
                    width: 8
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content

          - type: sample
            configYaml: |
              - type: panel-tr
                color: dodger-blue
                children:
                  - type: el
                    width: 4
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content
          - type: sample
            configYaml: |
              - type: panel-tr
                title: title
                color: dodger-blue
                gap: 1
                rightWidth: 1
                rightColor: golden-tainoi
                topCap: true
                bottomCap: true
                rightChildren:
                  - type: el
                    color: atomic-tangerine
                    height: 1
                topChildren:
                  - type: el
                    color: lilac
                    width: 1
                children:
                  - type: el
                    width: 8
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content

          - type: sample
            configYaml: |
              - type: panel-br
                color: dodger-blue
                children:
                  - type: el
                    width: 4
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content
          - type: sample
            configYaml: |
              - type: panel-br
                title: title
                color: dodger-blue
                gap: 1
                rightWidth: 1
                rightColor: golden-tainoi
                topCap: true
                bottomCap: true
                rightChildren:
                  - type: el
                    color: atomic-tangerine
                    height: 1
                bottomChildren:
                  - type: el
                    color: lilac
                    width: 1
                children:
                  - type: el
                    width: 8
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content

          - type: sample
            configYaml: |
              - type: panel-all
                color: dodger-blue
                children:
                  - type: el
                    width: 4
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content

          - type: sample
            configYaml: |
              - type: panel-all
                color: dodger-blue
                leftWidth: 1
                rightWidth: 1
                topHeight: 1
                bottomHeight: 1
                gap: 1
                title: Title
                topChildren:
                  - type: el
                    color: golden-tainoi
                    width: 1
                bottomChildren:
                  - type: el
                    color: golden-tainoi
                    width: 1
                leftChildren:
                  - type: el
                    color: golden-tainoi
                    height: 1
                rightChildren:
                  - type: el
                    color: golden-tainoi
                    height: 1
                children:
                  - type: el
                    width: 8
                    height: 4
                    color: eggplant
                    alignContent: middle-center
                    text: content

          - type: pill
            color: anakiwa
            nav: /demo/nav
            text: Navigation

      - showForNav: /demo/nav
        children:
          - type: sample
            configYaml: |
              - type: row
                children:
                  - type: pill
                    text: Nav
                    nav: /demo/nav/test
                    color: golden-tainoi
                  - type: el
                    showForNav: /demo/nav/test
                    marginLeft: 0.5
                    pad: 0.2
                    color: indian-red
                    text: Khaaaan!!!!

          - type: sample
            configYaml: |
              - type: pill
                text: Google
                nav: url:https://google.com
                color: golden-tainoi
              - type: pill
                text: Root Path
                nav: url:/ha-lcars-panel
                color: golden-tainoi
              - tag: a
                name: foo
              - type: pill
                text: Anchor
                nav: url:#foo
                color: golden-tainoi

          - type: pill
            color: lilac
            nav: /demo/state
            text: HA State

      - showForNav: /demo/state
        children:
          - type: sample
            configYaml: |
              - type: state-value
                entity: sun.sun
                attribute: elevation
          - type: sample
            configYaml: |
              - type: pill
                color: golden-tainoi
                children:
                  - type: state-value
                    entity: sun.sun
                    attribute: elevation
          - type: sample
            configYaml: |
              - type: state-color
                entity: sun.sun
                attribute: elevation
                color: golden-tainoi
                textColor: black
                min: -360
                max: 180
                text: Sun
          - type: sample
            configYaml: |
              - type: attribute-list
                entity: sun.sun
                textColor: lilac
                fontSize: 0.5
                lineHeight: 1
                animation: row-fill
