type: custom:ha-lcars-panel
disableAnimations: true
remoteRoot: /ha-lcars-panel
nav:
  - text: Demo
    children:
      - text: Setup
      - text: Unit
      - text: Colors
      - text: Layout
      - text: Panels
  - text: Samples
    children:
      - text: Sun
children:
  - showForNav: /home
    type: panel-tl
    fillLeftBottom: true
    children:
      - type: md
        textAnimation:
          type: typing
        content: |
          Greetings, captain.

          Welcome to HA LCARS.

          I am here to get you acquainted with the LCARS
          layout system.

          I can walk you through the system step-by-step, or you can jump right in to the API.
      - type: row
        gap: 1
        children:
          - type: pill
            nav: /demo/setup
            width: 6
            marginTop: 1
            text: Begin Demonstration
            animations:
              in:
                - type: grow-right
                  delay: 5
          - type: pill
            nav: /samples/index
            width: 6
            marginTop: 1
            text: Browse Samples
            color: 2
            animations:
              in:
                - type: grow-right
                  delay: 5
          - type: pill
            nav: /api
            width: 6
            marginTop: 1
            text: Browse API
            color: 3
            animations:
              in:
                - type: grow-right
                  delay: 5
  - showForNav: /demo
    type: nav-remote
    rootPath: /demo
  - showForNav: /samples
    type: remote
    url: ~/samples/index.yaml?raw
  - showForNav: /api
    type: panel-tl
    fillLeftBottom: true
    leftChildren:
      - type: el
        color: 2
        text: Home
        nav: /home
        textColor: black
      - type: el
        color: 3
        text: Demo
        nav: /demo/setup
        textColor: black
    children:
      - type: remote
        url: ~/api.yaml?raw
